const mongoose = require('mongoose');
const { ObjectId } = mongoose.Types;
const { getNextSequenceValue } = require('../service/sequenceService');

const getDefaultRoles = async () => {
  return [
    {
      roleId: await getNextSequenceValue('roleId'),
      name: 'Owner',
      viewOrder: true,
      editOrder: true,
      createOrder: true,
      viewPrice: true,
      viewShop: true,
      editShop: true,
      viewCustomer: true,
      editCustomer: true,
      administration: true,
      viewReports: true,
      addDressItem: true,
      payments: true,
      assignDressItem: true,
      manageOrderStatus: true,
      manageWorkShop: true,
    },
    {
      roleId: await getNextSequenceValue('roleId'),
      name: 'Shop Manager',
      viewOrder: true,
      editOrder: true,
      createOrder: true,
      viewPrice: true,
      viewShop: true,
      editShop: false,
      viewCustomer: true,
      editCustomer: false,
      administration: true,
      viewReports: true,
      addDressItem: true,
      payments: false,
      assignDressItem: true,
      manageOrderStatus: true,
      manageWorkShop: false,
    },
    {
      roleId: await getNextSequenceValue('roleId'),
      name: 'Staff',
      viewOrder: true,
      editOrder: false,
      createOrder: false,
      viewPrice: false,
      viewShop: false,
      editShop: false,
      viewCustomer: false,
      editCustomer: false,
      administration: false,
      viewReports: false,
      addDressItem: false,
      payments: false,
      assignDressItem: true,
      manageOrderStatus: true,
      manageWorkShop: false,
    },
    {
      roleId: await getNextSequenceValue('roleId'),
      name: 'Worker',
      viewOrder: true,
      editOrder: false,
      createOrder: false,
      viewPrice: false,
      viewShop: false,
      editShop: false,
      viewCustomer: false,
      editCustomer: false,
      administration: false,
      viewReports: false,
      addDressItem: false,
      payments: false,
      assignDressItem: false,
      manageOrderStatus: true,
      manageWorkShop: false,
    },
    {
      roleId: await getNextSequenceValue('roleId'),
      name: 'Cutting Master',
      viewOrder: true,
      editOrder: false,
      createOrder: false,
      viewPrice: false,
      viewShop: false,
      editShop: false,
      viewCustomer: false,
      editCustomer: false,
      administration: false,
      viewReports: false,
      addDressItem: false,
      payments: false,
      assignDressItem: false,
      manageOrderStatus: true,
      manageWorkShop: false,
    },
    {
      roleId: await getNextSequenceValue('roleId'),
      name: 'Tailor',
      viewOrder: true,
      editOrder: false,
      createOrder: false,
      viewPrice: false,
      viewShop: false,
      editShop: false,
      viewCustomer: false,
      editCustomer: false,
      administration: false,
      viewReports: false,
      addDressItem: false,
      payments: false,
      assignDressItem: false,
      manageOrderStatus: true,
      manageWorkShop: false,
    },
  ];
};

module.exports = { getDefaultRoles };
